# gradle
org.gradle.daemon=false
org.gradle.jvmargs=-Xmx3G
org.gradle.debug=false

# forge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
forge_version=21.1.217
forge_version_range=[21.1.217,)
loader_version_range=[1,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# mod
main_version=1
major_version=10
minor_version=0
mod_id=vampirism_integrations
mod_name=Vampirism Integrations
mod_license=LGPL-3.0
mod_group_id=de.teamlapen.vampirism_integrations
mod_authors=Maxanier
mod_description=Adds integration for Vampirism with several other mods
mod_url=https://vampirism.dev
mod_issue_tracker=https://github.com/TeamLapen/VampirismIntegrations/issues
modrinth_id=ygTFuViO
curseforge_id=282433
curseforge_slug=vampirism-integrations
pack_format_number=18

# properties will be overridden in gradle file
mod_version=""
type=""
classification=""


# If you want to enable / disable a dependency, you need to do the following:
# 1. Set the include_* variable to true or false
# 2. Set the version variable to the version you want to use
# 3. Add / remove the mod package to / from the .idea/compiler.xml
# 4. Add / remove the compat mod class to the CompatLoader in the main mod class
# dependencies
vampirism_mcversion=1.21
vampirism_version=1.10.3

include_biomes_o_plenty=true
bop_version=7251965
glitch_core_version=5660740

include_waila=true
include_waila_at_runtime=true
wthit_version=12.9.0
bad_packets_version=0.8.2

include_jade=true
include_jade_at_runtime=true
jade_version=6853386

include_immersive_engineering=true
immersiveengineering_fileid=6733669

include_evilcraft=true
evilcraft_fileid=7365340
cyclopscore_fileid=7365285

include_tough_as_nails=true
tan_version=5833252

include_nyctophobia=false
nyctophobia_fileid=4593078

#https://www.curseforge.com/minecraft/mc-mods/survive/files/
#https://www.curseforge.com/minecraft/mc-mods/unionlib/files
include_survive=true
include_survive_at_runtime=false
survive_version=1.21.1-10.1.11-NeoForge
unionlib_version=1.21.1-12.1.1-NeoForge
serene_seasons_version=6182596

include_crafttweaker=true
crafttweaker_version=1.21.1:21.0.35

include_minecraft_comes_alive=true
include_minecraft_comes_alive_at_runtime=true
mca_fileid=7278618

#https://www.curseforge.com/minecraft/mc-mods/minecolonies/files
#https://www.curseforge.com/minecraft/mc-mods/structurize/files
#https://www.curseforge.com/minecraft/mc-mods/domum-ornamentum/files
#https://www.curseforge.com/minecraft/mc-mods/blockui/files
#https://www.curseforge.com/minecraft/mc-mods/multi-piston/files
#https://www.curseforge.com/minecraft/mc-mods/towntalk/files
include_minecolonies=true
minecolonies_version=7384176
structurize_version=7421173
domum_ornamentum_version=7422835
blockui_version=6646615
multipiston_version=7097877
talktown_version=5653504

#https://www.curseforge.com/minecraft/mc-mods/mekanism/files/
include_mekanism=true
mekanism_version=1.21.1-10.7.17.83

#Optional runtime
include_guide_api=true
guideapi_version=1.21-2.3.0

#https://www.curseforge.com/minecraft/mc-mods/jei/files
include_jei=true
jei_version=19.27.0.336

#https://www.curseforge.com/minecraft/mc-mods/terrablender-neoforge
include_terrablender=true
terrablender_version=4.1.0.8

#https://www.curseforge.com/minecraft/mc-mods/architectury-api/files
include_architectury=true
architectury_version=13.0.8

#https://www.curseforge.com/minecraft/mc-mods/cold-sweat/files/
include_cold_sweat=true
coldsweat_fileid=7370181

#https://www.curseforge.com/minecraft/mc-mods/guard-villagers/files/
include_guard_villagers=true
include_guard_villagers_at_runtime=true
guardvillagers_fileid=7306932

#https://www.curseforge.com/minecraft/mc-mods/choicetheorems-overhauled-village/files/
#https://www.curseforge.com/minecraft/mc-mods/lithostitched/files
include_ctov=true
ctov_fileid=7412721
lithostitched_fileid=7395055

#https://www.curseforge.com/minecraft/mc-mods/capybara-uam/files/6453485
include_capybara=true
capybara_fileid=6453485

#### Old

include_consecration=false
consecration_fileid=4638141

include_betteranimalsplus=false
betteranimalsplus_fileid=4318518

include_player_companion=false
playercompanion_fileid=4693315

include_bloodmagic=false
bloodmagic_fileid=3477631
bloodmagic_api_fileid=3477632

include_betteranimals=false
betteranimals_fileid=3830935

include_tinkers_construction=false
tconstruct_version=1.18.2-3.5.1.31
mantle_version=1.18.1-1.8.37

include_diet=false
diet_fileid=4634780