# gradle
org.gradle.daemon=false
org.gradle.jvmargs=-Xmx3G
org.gradle.debug=false

# forge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
forge_version=21.1.73
forge_version_range=[21.1.73,)
loader_version_range=[1,)
parchment_minecraft_version=1.21
parchment_mappings_version=2024.07.28

# mod
main_version=1
major_version=9
minor_version=2
mod_id=vampirism_integrations
mod_name=Vampirism Integrations
mod_license=LGPL-3.0
mod_group_id=de.teamlapen.vampirism_integrations
mod_authors=Maxanier
mod_description=Adds integration for Vampirism with several other mods
mod_url=https://vampirism.dev
mod_issue_tracker=https://github.com/TeamLapen/VampirismIntegrations/issues
modrinth_id=ygTFuViO
curseforge_id=282433
curseforge_slug=vampirism-integrations
pack_format_number=18

# properties will be overridden in gradle file
mod_version=""
type=""
classification=""


# If you want to enable / disable a dependency, you need to do the following:
# 1. Set the include_* variable to true or false
# 2. Set the version variable to the version you want to use
# 3. Add / remove the mod package to / from the .idea/compiler.xml
# 4. Add / remove the compat mod class to the CompatLoader in the main mod class
# dependencies
vampirism_mcversion=1.21
vampirism_version=1.10.3

include_biomes_o_plenty=true
bop_version=5855568
glitch_core_version=5660740

include_waila=true
wthit_version=12.4.2
bad_packets_version=0.8.1

include_jade=true
jade_version=5846105

include_immersive_engineering=true
immersiveengineering_fileid=5828000

include_evilcraft=true
evilcraft_fileid=5841589
cyclopscore_fileid=5868793

include_tough_as_nails=true
tan_version=5833252

include_nyctophobia=false
nyctophobia_fileid=4593078

include_survive=true
survive_version=1.21.1-10.1.3-NeoForge
unionlib_version=1.21.1-12.0.7-NeoForge
serene_seasons_version=5753503

include_crafttweaker=true
crafttweaker_version=1.21.1:21.0.5

include_minecraft_comes_alive=false
mca_fileid=4675848

include_minecolonies=true
minecolonies_version=5864965
structurize_version=5853196
domum_ornamentum_version=5764083
blockui_version=5782223
multipiston_version=5783614
talktown_version=5653504

include_mekanism=false
mekanism_version=1.20.4-10.5.20.41

#Optional runtime
include_guide_api=true
guideapi_version=1.21-2.3.0-beta.1

include_jei=true
jei_version=19.21.0.247

include_terrablender=true
terrablender_version=4.1.0.5

include_architectury=true
architectury_version=13.0.8

include_cold_sweat=true
coldsweat_fileid=5858987

include_guard_villagers=true
guardvillagers_fileid=5605256

include_ctov=true
ctov_fileid=6459807
lithostitched_fileid=6533426

#### Old

include_consecration=false
consecration_fileid=4638141

include_betteranimalsplus=false
betteranimalsplus_fileid=4318518

include_player_companion=false
playercompanion_fileid=4693315

include_bloodmagic=false
bloodmagic_fileid=3477631
bloodmagic_api_fileid=3477632

include_betteranimals=false
betteranimals_fileid=3830935

include_tinkers_construction=false
tconstruct_version=1.18.2-3.5.1.31
mantle_version=1.18.1-1.8.37

include_diet=false
diet_fileid=4634780