
apply plugin: 'maven-publish'
tasks.withType(GenerateModuleMetadata) {
    enabled = false
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId project.group
            artifactId project.mod_id
            version project.version
            from components.java

            // Allows the maven pom file to be modified.
            pom.withXml {
                // Go through all the dependencies.
                asNode().dependencies.dependency.each { dep ->

                    // Check if the dependency has been mapped with MCP
                    if (dep.version.last().value().last().contains('_mapped_snapshot_') || dep.version.last().value().last().contains('_mapped_stable_') || dep.version.last().value().last().contains('_mapped_official_') || dep.version.last().value().last().contains('_mapped_parchment_')) {
                        // Remove the MCP mapped artifact from the dependency list.
                        println 'Surpressing MCP mapped artifact ' + dep.artifactId.last().value().last() + ' from maven dependencies.'
                        assert dep.parent().remove(dep)
                    }
                }
            }

            pom {
                description = 'An Minecraft mod that integrating Vampirism with other mods'

                scm {
                    url = 'https://github.com/TeamLapen/VampirismIntegrations'
                    connection = 'scm:git:git://github.com/TeamLapen/VampirismIntegrations.git'
                    developerConnection = 'scm:git:git@github.com:TeamLapen/VampirismIntegrations.git'
                }

                issueManagement {
                    system = 'github'
                    url = 'https://github.com/TeamLapen/VampirismIntegrations/issues'
                }
                developers {
                    developer {
                        id = 'maxanier'
                        name = 'maxanier'
                        roles = ["developer"]
                    }
                }

            }

            artifact sourcesJar
            artifact javadocJar

        }
    }

    repositories {
        maven {
            // Sets the login credentials for your maven.
            credentials {
                username findProperty('maxanier_maven_alias')
                password findProperty('maxanier_maven_token')
            }

            // Sets the maven URL
            url findProperty('maxanier_maven_url')
        }
    }
}

tasks.register('checkIfPublicVersion') {
    doFirst {
        if (project.classification != "public") {
            throw new PublishException("Trying to publish a version that is not intended for public release")
        }
    }
}

tasks.register('publishAll') {
    dependsOn('build')
    dependsOn('checkIfPublicVersion')
    dependsOn('publish')
    dependsOn('publishMods')
}

tasks.publishMods.dependsOn(checkIfPublicVersion)

publishMods {
    type = project.type == "beta" ? BETA: project.type == "release" ? STABLE : ALPHA
    changelog = !(findProperty("CHANGELOG") ?: "").toString().isEmpty() ? getProperty("CHANGELOG") : type != ALPHA ? "" : "This version should not be used in your 'productive' world. It contains the latest features, but also the latest bugs.\n Probably not all features are finished.\n To see what might have changed browse the latest commits."
    file = jar.archiveFile
    modLoaders.add("neoforge")
    version = "${project.minecraft_version}-${project.mod_version}"
    displayName = "VampirismIntegrations-${project.minecraft_version}-${project.mod_version}"
    dryRun = !(project.hasProperty("MODRINTH_API") && project.hasProperty("CURSEFORGE_API"))

    modrinth {
        accessToken = findProperty("MODRINTH_API") ?: "DUMMY"
        projectId = project.modrinth_id
        minecraftVersions.add(project.minecraft_version)

        requires("vampirism")
        optional("better-combat")
        optional("biomes-o-plenty")
        optional("ct-overhaul-village")
        optional("tough-as-nails")
        optional("evilcraft")
        optional("wthit")
        optional("survive")
        optional("crafttweaker")
        optional("jade")
        optional("cold-sweat")
        optional("guard-villagers")
        optional("better-combat")

    }

    curseforge {
        accessToken = findProperty("CURSEFORGE_API") ?: "DUMMY"
        projectId = project.curseforge_id
        minecraftVersions.add(project.minecraft_version)
        projectSlug = project.curseforge_slug
        requires("vampirism-become-a-vampire")
        optional("better-combat-by-daedelus")


        optional("choicetheorems-overhauled-village")
        if (project.include_biomes_o_plenty.toBoolean()) {
            optional( 'biomes-o-plenty')
        }
        if (project.include_waila.toBoolean()) {
            optional( 'waila')
        }
        if (project.include_immersive_engineering.toBoolean()) {
            optional( 'immersive-engineering')
        }
        if (project.include_evilcraft.toBoolean()) {
            optional( 'evilcraft')
        }
        if (project.include_tough_as_nails.toBoolean()) {
            optional( 'tough-as-nails')
        }
        if (project.include_nyctophobia.toBoolean()) {
            optional( 'nyctophobia-forge')
        }
        if (project.include_survive.toBoolean()) {
            optional( 'survive')
        }
        if (project.include_diet.toBoolean()) {
            optional( 'diet')
        }
        if (project.include_tinkers_construction.toBoolean()) {
            optional( 'tinkers-construct')
        }
        if (project.include_crafttweaker.toBoolean()) {
            optional( 'crafttweaker')
        }
        if (project.include_betteranimalsplus.toBoolean()) {
            optional( 'betteranimalsplus')
        }
        if (project.include_consecration.toBoolean()) {
            optional( 'consecration')
        }
        if (project.include_minecraft_comes_alive.toBoolean()) {
            optional( 'minecraft-comes-alive-reborn')
        }
        if (project.include_minecolonies.toBoolean()) {
            optional( 'minecolonies')
        }
        if (project.include_player_companion.toBoolean()) {
            optional( 'player-companions')
        }
        if (project.include_betteranimals.toBoolean()) {
            optional( 'better-animal-models')
        }
        if (project.include_bloodmagic.toBoolean()) {
            optional( 'blood-magic')
        }
        if (project.include_mekanism.toBoolean()) {
            optional( 'mekanism')
        }
        if (project.include_guide_api.toBoolean()) {
            optional( 'guide-api-village-and-pillage')
        }
        if (project.include_jei.toBoolean()) {
            optional( 'jei')
        }
        if (project.include_terrablender.toBoolean()) {
            optional( 'terrablender')
        }
        if (project.include_architectury.toBoolean()) {
            optional( 'architectury-api')
        }
        if (project.include_jade.toBoolean()) {
            optional( 'jade')
        }
        if (project.include_cold_sweat.toBoolean()) {
            optional( 'cold-sweat')
        }
        if (project.include_guard_villagers.toBoolean()) {
            optional( 'guard-villagers')
        }
        if (project.include_capybara.toBoolean()) {
            optional( 'capybara-uam')
        }
        if (project.include_better_combat.toBoolean()) {
            optional( 'better-combat')
        }
    }
}